
rm -rf $PRODUCT/app/AEXWallpaperStub
rm -rf $PRODUCT/app/ARCore
rm -rf $PRODUCT/app/AboutBliss
rm -rf $PRODUCT/app/Abstruct
rm -rf $PRODUCT/app/AudioRecorder
rm -rf $PRODUCT/app/BasicDreams
rm -rf $PRODUCT/app/BlissStatistics
rm -rf $PRODUCT/app/BookmarkProvider
rm -rf $PRODUCT/app/Bromite
rm -rf $PRODUCT/app/Browser
rm -rf $PRODUCT/app/Browser2
rm -rf $PRODUCT/app/Calendar
rm -rf $PRODUCT/app/Chrome
rm -rf $PRODUCT/app/Chrome-Stub
rm -rf $PRODUCT/app/Dashboard
rm -rf $PRODUCT/app/DevicePolicyPrebuilt
rm -rf $PRODUCT/app/DiagnosticsToolPrebuilt
rm -rf $PRODUCT/app/Drive
rm -rf $PRODUCT/app/Duo
rm -rf $PRODUCT/app/Email
rm -rf $PRODUCT/app/EmergencyInfo
rm -rf $PRODUCT/app/Etar
rm -rf $PRODUCT/app/ExactCalculator
rm -rf $PRODUCT/app/Exchange2
rm -rf $PRODUCT/app/FM2
rm -rf $PRODUCT/app/FMPlayer
rm -rf $PRODUCT/app/Gallery
rm -rf $PRODUCT/app/Gallery2
rm -rf $PRODUCT/app/GalleryGo
rm -rf $PRODUCT/app/GalleryGoPrebuilt
rm -rf $PRODUCT/app/Gmail2
rm -rf $PRODUCT/app/GoogleOne
rm -rf $PRODUCT/app/GoogleTTS
rm -rf $PRODUCT/app/GrapheneCamera
rm -rf $PRODUCT/app/Jelly
rm -rf $PRODUCT/app/Maps
rm -rf $PRODUCT/app/Music
rm -rf $PRODUCT/app/Music2
rm -rf $PRODUCT/app/PartnerBookmark
rm -rf $PRODUCT/app/Partnerbookmark
rm -rf $PRODUCT/app/PhotoTable
rm -rf $PRODUCT/app/Photos
rm -rf $PRODUCT/app/PlayAutoInstallConfig
rm -rf $PRODUCT/app/PrebuiltBugle
rm -rf $PRODUCT/app/PrebuiltGmail
rm -rf $PRODUCT/app/PrebuiltKeep
rm -rf $PRODUCT/app/QPGallery
rm -rf $PRODUCT/app/QtiSoundRecorder
rm -rf $PRODUCT/app/Recorder
rm -rf $PRODUCT/app/RetroMusic
rm -rf $PRODUCT/app/RetroMusicPlayer
rm -rf $PRODUCT/app/SatisPay
rm -rf $PRODUCT/app/SeedVault
rm -rf $PRODUCT/app/ShishufiedWalls
rm -rf $PRODUCT/app/SimpleGallery
rm -rf $PRODUCT/app/SoundAmplifierPrebuilt
rm -rf $PRODUCT/app/SpeechServicesByGoogle
rm -rf $PRODUCT/app/Tycho
rm -rf $PRODUCT/app/Velvet
rm -rf $PRODUCT/app/Via
rm -rf $PRODUCT/app/Videos
rm -rf $PRODUCT/app/WallpaperZone
rm -rf $PRODUCT/app/WallpapersBReel2020
rm -rf $PRODUCT/app/WallpapersBReel2020a
rm -rf $PRODUCT/app/WellbeingPrebuilt
rm -rf $PRODUCT/app/XPerienceWallpapers
rm -rf $PRODUCT/app/YTMusic
rm -rf $PRODUCT/app/YTMusicSetupWizard
rm -rf $PRODUCT/app/YouTube
rm -rf $PRODUCT/app/YouTubeMusicPrebuilt
rm -rf $PRODUCT/app/arcore
rm -rf $PRODUCT/app/com.google.mainline.adservices
rm -rf $PRODUCT/app/com.google.mainline.telemetry
rm -rf $PRODUCT/app/crDroidMusic
rm -rf $PRODUCT/app/facebook-appmanager
rm -rf $PRODUCT/app/talkback
rm -rf $PRODUCT/overlay/ChromeOverlay
rm -rf $PRODUCT/overlay/TelegramOverlay
rm -rf $PRODUCT/overlay/WhatsAppOverlay
rm -rf $PRODUCT/priv-app/AmazonAppManager
rm -rf $PRODUCT/priv-app/AncientWallpaperZone
rm -rf $PRODUCT/priv-app/AndroidAutoStub
rm -rf $PRODUCT/priv-app/AndroidAutoStubPrebuilt
rm -rf $PRODUCT/priv-app/AndroidMigratePrebuilt
rm -rf $PRODUCT/priv-app/AudioFx_v2
rm -rf $PRODUCT/priv-app/Chrome
rm -rf $PRODUCT/priv-app/ChromeHomePageProvider
rm -rf $PRODUCT/priv-app/ClaroContenedorStub
rm -rf $PRODUCT/priv-app/DuckDuckGo
rm -rf $PRODUCT/priv-app/Eleven
rm -rf $PRODUCT/priv-app/Email
rm -rf $PRODUCT/priv-app/EmergencyInfo
rm -rf $PRODUCT/priv-app/FM2
rm -rf $PRODUCT/priv-app/FMPlayer
rm -rf $PRODUCT/priv-app/Gallery2
rm -rf $PRODUCT/priv-app/GoogleRestore
rm -rf $PRODUCT/priv-app/GoogleRestorePrebuilt
rm -rf $PRODUCT/priv-app/GuideMe
rm -rf $PRODUCT/priv-app/HelpRtcPrebuilt
rm -rf $PRODUCT/priv-app/HotwordEnrollment*
rm -rf $PRODUCT/priv-app/HotwordEnrollmentOKGoogleHEXAGON
rm -rf $PRODUCT/priv-app/HotwordEnrollmentXGoogleHEXAGON
rm -rf $PRODUCT/priv-app/MatLog
rm -rf $PRODUCT/priv-app/MusicFX
rm -rf $PRODUCT/priv-app/NovaBugreportWrapper
rm -rf $PRODUCT/priv-app/OmniSwitch
rm -rf $PRODUCT/priv-app/PixelLiveWallpaperPrebuilt
rm -rf $PRODUCT/priv-app/PixelSetupWizard
rm -rf $PRODUCT/priv-app/PrebuiltBugle
rm -rf $PRODUCT/priv-app/QtiSoundRecorder
rm -rf $PRODUCT/priv-app/RecorderPrebuilt
rm -rf $PRODUCT/priv-app/RetroMusicPlayer
rm -rf $PRODUCT/priv-app/SafetyHub
rm -rf $PRODUCT/priv-app/SafetyHubPrebuilt
rm -rf $PRODUCT/priv-app/ScribePrebuilt
rm -rf $PRODUCT/priv-app/SecurityHubPrebuilt
rm -rf $PRODUCT/priv-app/SeedVault
rm -rf $PRODUCT/priv-app/SetupWizard
rm -rf $PRODUCT/priv-app/SetupWizardPrebuilt
rm -rf $PRODUCT/priv-app/SimpleCalendar
rm -rf $PRODUCT/priv-app/SimpleGallery
rm -rf $PRODUCT/priv-app/Snap
rm -rf $PRODUCT/priv-app/Tag
rm -rf $PRODUCT/priv-app/TipsPrebuilt
rm -rf $PRODUCT/priv-app/Velvet
rm -rf $PRODUCT/priv-app/Via
rm -rf $PRODUCT/priv-app/ViaBrowser
rm -rf $PRODUCT/priv-app/VinylMusicPlayer
rm -rf $PRODUCT/priv-app/Wellbeing
rm -rf $PRODUCT/priv-app/WellbeingPreBuilt
rm -rf $PRODUCT/priv-app/WellbeingPrebuilt
rm -rf $PRODUCT/priv-app/arcore
rm -rf $PRODUCT/priv-app/crDroidMusic
rm -rf $PRODUCT/priv-app/facebook-installer
rm -rf $PRODUCT/priv-app/facebook-services
rm -rf $PRODUCT/priv-app/stats
rm -rf $SYSTEM/app/AEXPapers
rm -rf $SYSTEM/app/AbleMusic
rm -rf $SYSTEM/app/Abstruct
rm -rf $SYSTEM/app/Aves
rm -rf $SYSTEM/app/BasicDreams
rm -rf $SYSTEM/app/BlissPapers
rm -rf $SYSTEM/app/BlissUpdater
rm -rf $SYSTEM/app/BookmarkProvider
rm -rf $SYSTEM/app/Browser
rm -rf $SYSTEM/app/Bug2GoStub
rm -rf $SYSTEM/app/BuiltInPrintService
rm -rf $SYSTEM/app/Chromium
rm -rf $SYSTEM/app/CloudPrint
rm -rf $SYSTEM/app/ColtPapers
rm -rf $SYSTEM/app/DuckDuckGo
rm -rf $SYSTEM/app/Duckduckgo
rm -rf $SYSTEM/app/EggGame
rm -rf $SYSTEM/app/Email
rm -rf $SYSTEM/app/Exchange2
rm -rf $SYSTEM/app/FM2
rm -rf $SYSTEM/app/FMRadioService
rm -rf $SYSTEM/app/Gallery
rm -rf $SYSTEM/app/GooglePrintRecommendationService
rm -rf $SYSTEM/app/GugelClock
rm -rf $SYSTEM/app/Jelly
rm -rf $SYSTEM/app/Kiwi
rm -rf $SYSTEM/app/MiXplorer
rm -rf $SYSTEM/app/Music
rm -rf $SYSTEM/app/MusicPlayerGO
rm -rf $SYSTEM/app/PartnerBookmark
rm -rf $SYSTEM/app/Partnerbookmark
rm -rf $SYSTEM/app/Phonograph
rm -rf $SYSTEM/app/PhotoTable
rm -rf $SYSTEM/app/PrintRecommendationService
rm -rf $SYSTEM/app/PrintSpooler
rm -rf $SYSTEM/app/QPGallery
rm -rf $SYSTEM/app/RetroMusic
rm -rf $SYSTEM/app/RetroMusicPlayer
rm -rf $SYSTEM/app/RetroMusicPlayerPrebuilt
rm -rf $SYSTEM/app/SeedVault
rm -rf $SYSTEM/app/SimpleCalendar
rm -rf $SYSTEM/app/SimpleGallery
rm -rf $SYSTEM/app/StagWalls
rm -rf $SYSTEM/app/Superiorwalls
rm -rf $SYSTEM/app/TilesWallpaper
rm -rf $SYSTEM/app/VanillaMusic
rm -rf $SYSTEM/app/Velvet
rm -rf $SYSTEM/app/Via
rm -rf $SYSTEM/app/ViaBrowser
rm -rf $SYSTEM/app/WellbeingPrebuilt
rm -rf $SYSTEM/app/Yunikon
rm -rf $SYSTEM/app/arcore
rm -rf $SYSTEM/app/crDroidMusic
rm -rf $SYSTEM/app/facebook-appmanager
rm -rf $SYSTEM/priv-app/AudioFX
rm -rf $SYSTEM/priv-app/BlissUpdater
rm -rf $SYSTEM/priv-app/Calendar
rm -rf $SYSTEM/priv-app/DigitalWellbeing
rm -rf $SYSTEM/priv-app/EasySetup
rm -rf $SYSTEM/priv-app/Eleven
rm -rf $SYSTEM/priv-app/Email
rm -rf $SYSTEM/priv-app/FM2
rm -rf $SYSTEM/priv-app/Gallery2
rm -rf $SYSTEM/priv-app/MatLog
rm -rf $SYSTEM/priv-app/MetroMusicPlayer
rm -rf $SYSTEM/priv-app/MusicFX
rm -rf $SYSTEM/priv-app/OmniSwitch
rm -rf $SYSTEM/priv-app/OneDrive_Samsung_v3
rm -rf $SYSTEM/priv-app/RetroMusicPlayerPrebuilt
rm -rf $SYSTEM/priv-app/SamsungCloudClient
rm -rf $SYSTEM/priv-app/SeedVault
rm -rf $SYSTEM/priv-app/Seedvault
rm -rf $SYSTEM/priv-app/SetupWizard
rm -rf $SYSTEM/priv-app/Snap
rm -rf $SYSTEM/priv-app/Tag
rm -rf $SYSTEM/priv-app/Velvet
rm -rf $SYSTEM/priv-app/Via
rm -rf $SYSTEM/priv-app/VinylMusicPlayer
rm -rf $SYSTEM/priv-app/WellbeingPrebuilt
rm -rf $SYSTEM/priv-app/arcore
rm -rf $SYSTEM/priv-app/crDroidMusic
rm -rf $SYSTEM/priv-app/stats
rm -rf $SYSTEM_EXT/app/EmergencyInfo
rm -rf $SYSTEM_EXT/app/EmergencyInfoGoogleNoUi
rm -rf $SYSTEM_EXT/app/FM2
rm -rf $SYSTEM_EXT/app/FMRadioService
rm -rf $SYSTEM_EXT/app/Papers
rm -rf $SYSTEM_EXT/app/Photos
rm -rf $SYSTEM_EXT/app/PrebuiltBugle
rm -rf $SYSTEM_EXT/app/SeedVault
rm -rf $SYSTEM_EXT/app/Superiorwalls
rm -rf $SYSTEM_EXT/priv-app/AndroidAutoStubPrebuilt
rm -rf $SYSTEM_EXT/priv-app/AudioFX
rm -rf $SYSTEM_EXT/priv-app/ChromeHomePageProvider
rm -rf $SYSTEM_EXT/priv-app/EmergencyInfo
rm -rf $SYSTEM_EXT/priv-app/FM2
rm -rf $SYSTEM_EXT/priv-app/Gallery2
rm -rf $SYSTEM_EXT/priv-app/GoogleRestore
rm -rf $SYSTEM_EXT/priv-app/Leaflet
rm -rf $SYSTEM_EXT/priv-app/MatLog
rm -rf $SYSTEM_EXT/priv-app/Music
rm -rf $SYSTEM_EXT/priv-app/PixelSetupWizard
rm -rf $SYSTEM_EXT/priv-app/SeedVault
rm -rf $SYSTEM_EXT/priv-app/Seedvault
rm -rf $SYSTEM_EXT/priv-app/SetupWizard
rm -rf $SYSTEM_EXT/priv-app/Snap
rm -rf $SYSTEM_EXT/priv-app/Updates
rm -rf $SYSTEM_EXT/priv-app/WellbeingPrebuilt
