rm -rf $PRODUCT/app/Lawnfeed
rm -rf $PRODUCT/app/Lawnicons
rm -rf $PRODUCT/overlay/PixelLauncherCustomOverlay
rm -rf $PRODUCT/overlay/PixelLauncherIconsOverlay
rm -rf $PRODUCT/overlay/PixelRecentsProvider
rm -rf $PRODUCT/overlay/ThemedIconsOverlay
rm -rf $PRODUCT/priv-app/NexusLauncherRelease
rm -rf $PRODUCT/priv-app/ParanoidQuickStep
rm -rf $PRODUCT/priv-app/ShadyQuickStep
rm -rf $PRODUCT/priv-app/TrebuchetQuickStep
rm -rf $SYSTEM/priv-app/AsusLauncherDev
rm -rf $SYSTEM/priv-app/Lawnchair
rm -rf $SYSTEM/priv-app/NexusLauncherPrebuilt
rm -rf $SYSTEM_EXT/priv-app/DerpLauncherQuickStep
rm -rf $SYSTEM_EXT/priv-app/Launcher3QuickStep
rm -rf $SYSTEM_EXT/priv-app/Lawnchair
rm -rf $SYSTEM_EXT/priv-app/NexusLauncherRelease
rm -rf $SYSTEM_EXT/priv-app/ThemePicker
rm -rf $SYSTEM_EXT/priv-app/TrebuchetQuickStep
