rm -rf $SYSTEM_EXT/app/LogKit
rm -rf $SYSTEM_EXT/app/Olc
rm -rf $SYSTEM_ROOT/my_bigball/app/Omoji
rm -rf $SYSTEM_ROOT/my_heytap/app/ARCore
rm -rf $SYSTEM_ROOT/my_heytap/app/Chrome
rm -rf $SYSTEM_ROOT/my_heytap/app/Music
rm -rf $SYSTEM_ROOT/my_heytap/app/SpeechServicesByGoogle
rm -rf $SYSTEM_ROOT/my_heytap/app/talkback
rm -rf $SYSTEM_ROOT/my_heytap/non_overlay/priv-app/SetupWizard
rm -rf $SYSTEM_ROOT/my_heytap/priv-app/AndroidAutoStub
rm -rf $SYSTEM_ROOT/my_heytap/priv-app/GoogleRestore
rm -rf $SYSTEM_ROOT/my_heytap/priv-app/Velvet
rm -rf $SYSTEM_ROOT/my_heytap/priv-app/Wellbeing
rm -rf $SYSTEM_ROOT/my_product/app/HotwordEnrollment*
rm -rf $SYSTEM_ROOT/my_stock/app/ChildrenSpace
rm -rf $SYSTEM_ROOT/my_stock/app/OPlusSegurityKeyboard
rm -rf $SYSTEM_ROOT/my_stock/app/OplusOperationManual
rm -rf $SYSTEM_ROOT/my_stock/del-app/OPBreathMode
rm -rf $SYSTEM_ROOT/my_stock/del-app/OPNote
rm -rf $SYSTEM_ROOT/my_stock/priv-app/KeKeUserCenter
rm -rf $SYSTEM_ROOT/my_stock/priv-app/SOSHelper
