	#rm -rf $PRODUCT/etc/sysconfig/nexus.xml
	rm -rf $PRODUCT/etc/sysconfig/Notice
	rm -rf $PRODUCT/etc/sysconfig/Shift.xml
	rm -rf $PRODUCT/etc/sysconfig/nga.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_2016_exclusive.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2017.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2017_midyear.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2018.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2018_midyear.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2019.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2019_midyear.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2020.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2020_midyear.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2021.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2021_midyear.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2022.xml
	rm -rf $PRODUCT/etc/sysconfig/pixel_experience_2022_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/Notice
	rm -rf $SYSTEM/etc/sysconfig/Shift.xml
	rm -rf $SYSTEM/etc/sysconfig/google_exclusives_enable.xml
	rm -rf $SYSTEM/etc/sysconfig/nexus.xml
	rm -rf $SYSTEM/etc/sysconfig/nga.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_2016_exclusive.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2017.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2017_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2018.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2018_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2019.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2019_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2020.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2020_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2021.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2021_midyear.xml
	rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2022.xml	
	rm -rf $SYSTEM_EXT/etc/sysconfig/nexus.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/nga.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_2016_exclusive.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2017.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2017_midyear.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2018.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2018_midyear.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2019.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2019_midyear.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2020.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2020_midyear.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2021.xml
	rm -rf $SYSTEM_EXT/etc/sysconfig/pixel_experience_2021_midyear.xml
    rm -rf $PRODUCT/etc/sysconfig/google_exclusives_enable.xml
    rm -rf $SYSTEM/etc/sysconfig/pixel_experience_2022_midyear.xml
